databases:
  - name: horilla-db
    databaseName: horilla
    user: horilla
    plan: free

services:
  - type: web
    name: horilla
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn horilla.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: horilla-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.4"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
